/*

 BKG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\ATS\Documents\GBA\game_boy_tile_designer_2022\sprites_gb\bkg_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_mapWidth 40
#define bkg_mapHeight 18
#define bkg_mapBank 0

extern unsigned char bkg_map[];

/* End of BKG_MAP.H */
